version: 2
jobs:
  build-client:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Running linter
          command: |
            cd client/
            npm install
            npm run lint
      - run:
          name: Build the client
          command: docker build -t magicmaze/client:latest client/
  build-server:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Running linter
          command: |
            cd server/
            npm install
            npm run lint
      - run:
          name: Build the server
          command: docker build -t magicmaze/server:latest server/

workflows:
  version: 2
  build-server-client:
    jobs:
      - build-server
      - build-client
