version: '3'
services:
  web:
    # build: ../client/
    image: itsmewiththeface/magicmaze-client:latest
    env_file:
      - client_variables.env
    ports:
      - "5000:5000"
      - "80:3000"
  api:
    # build: ../server/
    image: itsmewiththeface/magicmaze-server:latest
    env_file:
      - server_variables.env
    ports:
      - "8000:8000"
  redis:
    image: "redis:alpine"
